const FILE_HEADER = "IDCLIENT;NO_CARTE;DAT_CRE_CARTE;DAT_MAJ_CARTE;MAG_RATTACHEMENT;CODE_ETAB_RATTACH;MAG_OUVERTURE;CODE_ETAB_OUV;ORIGINE;TYPE_CLIENT;CIV;NOM;SECOND_NOM;PRENOM;PATRONYME;PAYS_CLIENT;LANGUE;NIF;NO_RUE;ADRESSE1;ADRESSE2;TYPE_VOIE;CP;LOC;PAYS;PROVINCE;DAT_CRE_ADRESSE;DAT_MAJ_ADRESSE;FLAG_SUPPRIME_ADRESSE;NO_RUE_LIVRAISON;ADRESSE1_LIVRAISON;ADRESSE2_LIVRAISON;TYPE_VOIE_LIVRAISON;CP_LIVRAISON;LOC_LIVRAISON;PAYS_LIVRAISON;PROVINCE_LIVRAISON;DAT_CRE_ADRESSE_LIVRAISON;DAT_MAJ_ADRESSE_LIVRAISON;FLAG_SUPPRIME_ADRESSE_LIVRAISON;TEL;DAT_CRE_TEL;DAT_MAJ_TEL;FLAG_SUPPRIME_TEL;TEL_PORT;DAT_CRE_TEL_PORT;DAT_MAJ_TEL_PORT;FLAG_SUPPRIME_TEL_PORT;ADR_EMAIL;DAT_CRE_EMAIL;DAT_MAJ_EMAIL;FLAG_SUPPRIME_EMAIL;OPTIN_SMS;DATE_OPTIN_SMS;DATE_OPTOUT_SMS;OPTIN_SMS_PARTNER;DATE_OPTIN_SMS_PARTNER;DATE_OPTOUT_SMS_PARTNER;OPTIN_KIABI_EMAIL;DATE_OPTIN_KIABI_EMAIL;DATE_OPTOUT_KIABI_EMAIL;OPTIN_PART_EMAIL;DATE_OPTIN_PARTNER_EMAIL;DATE_OPTOUT_PARTNER_EMAIL;DAT_NAI_CLIENT;PRENOM_ENFANT1;DAT_NAI_ENFANT1;SEXE_ENFANT1;DAT_CRE_ENFANT1;DAT_MAJ_ENFANT1;FLAG_SUPPRIME_ENFANT1;PRENOM_ENFANT2;DAT_NAI_ENFANT2;SEXE_ENFANT2;DAT_CRE_ENFANT2;DAT_MAJ_ENFANT2;FLAG_SUPPRIME_ENFANT2;PRENOM_ENFANT3;DAT_NAI_ENFANT3;SEXE_ENFANT3;DAT_CRE_ENFANT3;DAT_MAJ_ENFANT3;FLAG_SUPPRIME_ENFANT3;PRENOM_ENFANT4;DAT_NAI_ENFANT4;SEXE_ENFANT4;DAT_CRE_ENFANT4;DAT_MAJ_ENFANT4;FLAG_SUPPRIME_ENFANT4;PRENOM_ENFANT5;DAT_NAI_ENFANT5;SEXE_ENFANT5;DAT_CRE_ENFANT5;DAT_MAJ_ENFANT5;FLAG_SUPPRIME_ENFANT5;DAT_CRE_CLIENT;DAT_MAJ_CLIENT;FLAG_SUPPRIME;FLAG_SUPPR_DONNEES";

const CIVILITE = {
    mr: ["MONSIEUR", "SIR", "MR", "MR."],
    mrs: ["MADAME", "MRS", "MRS."]
}

const FIELDS_LENGTH = {
    nom: 50,
    prenom: 50,
    zipCode: 10,
    city: 32,
    phone: 20,
    email: 72,
    children: 5
}

const FILE_CLIENT_SEPARATOR = {
    line: "\r\n",
    column: ";"
}

const FILE_CLIENT_PREFIX = "CUSPTK";
const FILE_CLIENT_EXT = ".csv.gpg";

const ENCRIPTION_KEY_PATH = `${__basedir}/files/key/kiabi-key`; 

module.exports = {
    FILE_HEADER,
    CIVILITE,
    FIELDS_LENGTH,
    FILE_CLIENT_SEPARATOR,
    FILE_CLIENT_PREFIX,
    FILE_CLIENT_EXT,
    ENCRIPTION_KEY_PATH
}